version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: music-library
    ports:
      - '3306:3306'
    volumes:
      - music-library:/var/lib/mysql

volumes:
  music-library:
