const bioPhrases = [
	'Exploring the depths of sound and rhythm.',
	'A unique voice in the contemporary music scene.',
	'Blending genres for a fresh musical experience.',
	'Music is my canvas, and notes are my paint.',
	'Crafting melodies that resonate with the soul.',
	'Harnessing the power of melody to tell compelling stories.',
	'A sonic adventurer, always seeking new horizons in music.',
	'Blending traditional rhythms with modern beats.',
	'Elevating the ordinary to extraordinary through music.',
	'A symphony of emotions expressed through sound.',
	'Revolutionizing the music scene with innovative compositions.',
	'Where words fail, my music speaks.',
	'Crafting soundscapes that transport listeners to another world.',
	'A confluence of cultural beats and contemporary tunes.',
	'Striking chords that resonate across generations.',
	'An alchemist of harmonies, transforming notes into gold.',
	'Breathing new life into classic genres.',
	'A maestro of melodies, orchestrating auditory bliss.',
	'Pushing the boundaries of sound with each note.',
	'Creating a tapestry of tunes that celebrates diversity.',
	'A journey through the spectrum of sound in every album.',
	'Uniting fans around the globe with universal rhythms.',
	'A visionary in the world of music, redefining genres.',
	'Transcending language barriers through the universal language of music.',
	'Sculpting soundwaves into masterpieces of auditory art.',
	'Igniting the stage with electrifying performances.',
	'Weaving lyrical magic into every song.',
	'Pioneering new paths in the musical landscape.',
	'A harmonious blend of passion and creativity.',
	'The heartbeat of a new generation of music lovers.',
	'Delivering soul-stirring tunes that linger in the mind.',
	'A tapestry of rhythms that echo the pulse of life.',
	'An endless quest for musical perfection.',
	'Crafting a unique sonic identity in every track.',
	'A beacon of innovation in the world of sound.',
	'Melodies that capture the essence of human emotion.',
	'Redefining what it means to be an artist in the digital age.',
	'An odyssey of sound that defies conventions.',
	'The architect of aural landscapes that inspire and captivate.',
	'A voice that echoes the sentiments of a generation.'
];

const artistBios: Record<string, string> = {
	Dennis: 'Mastering the art of electronic beats and vibrant rhythms.',
	D4vd: 'Bringing fresh energy and innovative sounds to the music scene.',
	Yandel: 'A powerhouse of reggaeton, blending rhythms that move the soul.',
	'Yahritza Y Su Esencia': 'Infusing traditional melodies with youthful vigor.',
	'Vance Joy': 'Crafting folk-pop anthems that resonate with heartfelt sincerity.',
	"Tyler The Creator": 'Pushing the boundaries of music with unique style and bold lyrics.',
	'Troye Sivan': 'A voice that encapsulates the spirit of modern pop.',
	'Tom Odell': 'Stirring emotions with piano-driven melodies and poetic lyrics.',
	'The Weeknd': 'A trailblazer in the world of R&B, constantly redefining the genre.',
	'The Neighbourhood': 'Melding alternative rock with introspective lyrics.',
	'Taylor Swift': 'A storytelling icon, weaving life experiences into musical masterpieces.',
	Tainy: 'Revolutionizing reggaeton and Latin music with groundbreaking production.',
	'Sam Smith': 'A soulful voice delivering deep emotional resonance.',
	SZA: 'An avant-garde R&B artist painting vivid stories through her music.',
	Rma: 'Pioneering new sounds and delivering electrifying performances.',
	'Rauw Alejandro': 'A fusion of Latin trap and reggaeton, setting the stage on fire.',
	Quevedo: 'Merging lyrical depth with compelling urban beats.',
	'Post Malone': 'Blurring genre lines with his unique blend of hip-hop and pop.',
	PinkPantheress: 'Redefining pop music with her distinct sound and style.',
	'Peso Pluma': 'Infusing music with energetic beats and captivating lyrics.',
	'Peggy Gou': 'A dynamic force in the electronic music scene, known for her eclectic mixes.',
	Ozuna: 'Dominating reggaeton and Latin trap with catchy tunes and charismatic energy.',
	OneRepublic: 'Delivering anthemic pop-rock tracks that resonate globally.',
	'Olivia Rodrigo': 'A new voice in pop, channeling raw emotions into her songs.',
	'Nicki Minaj': 'A rap icon known for her versatile flow and bold personality.',
	NewJeans: 'Redefining K-pop with their fresh style and energetic performances.',
	'Myke Towers': 'A rising star in Latin music, known for his distinctive flow.',
	'Morgan Wallen': 'Blending country charm with rock energy to create memorable tunes.',
	'Miley Cyrus': 'Constantly evolving, from pop sensation to rock powerhouse.',
	'Mc Livinho': 'Bringing Brazilian funk rhythms to the global music stage.',
	Marshmello: 'An electronic music maestro known for his infectious beats.',
	'Maria Becerra': 'A vibrant new voice in Latin pop, fusing catchy melodies with urban sounds.',
	'Manuel Turizo': 'A standout in reggaeton, known for his smooth voice and romantic lyrics.',
	'Luke Combs': 'Reigniting country music with his powerful voice and relatable songs.',
	Libianca: 'A fresh talent, blending Afrobeat rhythms with soulful melodies.',
	'Lewis Capaldi': 'Delivering emotional ballads with his powerful, soul-stirring voice.',
	Latto: 'A bold and dynamic rapper, making waves with her fiery lyrics.',
	'Lana Del Rey': 'An ethereal presence in music, known for her cinematic and nostalgic sound.',
	'Karol G': 'A queen of reggaeton, known for her empowering anthems and vibrant performances.',
	'Kali Uchis': 'A fusion of soul, R&B, and Latin beats, creating a unique sound experience.',
	'Justin Bieber': 'From teen idol to global pop star, constantly evolving his sound.',
	'Junior H': 'A fresh voice in regional Mexican music, blending tradition with modernity.',
	'Jung Kook':
		'A member of BTS, captivating fans with his powerful vocals and dynamic performances.',
	Jimin: 'Known for his expressive voice and mesmerizing dance moves in BTS.',
	Jain: 'Mixing electronic beats with multicultural influences to create a unique sound.',
	JVKE: 'A rising star, blending heartfelt lyrics with catchy pop melodies.',
	'J. Cole': 'A profound lyricist and rapper, known for his thought-provoking music.',
	'Harry Styles': 'Defining modern pop-rock with his charismatic presence and bold choices.',
	Gunna: 'A trailblazer in trap music, known for his smooth flow and catchy beats.',
	'Glass Animals': 'Crafting psychedelic pop with intricate melodies and immersive soundscapes.',
	'Gabito Ballesteros':
		'A vibrant force in the music scene, infusing every performance with passion.',
	'Fuerza Regida':
		'Revitalizing the regional music scene with their unique sound and powerful lyrics.',
	'Fifty Fifty': 'Blending a rich array of genres to create a unique musical experience.',
	Feid: 'A standout artist in urban Latin music, known for his catchy melodies and smooth vocals.',
	'Eslabon Armado': 'Bringing a fresh take to traditional music, weaving in modern influences.',
	'Em Beihold': 'A voice that captivates, combining depth of lyrics with a melodic finesse.',
	'Dua Lipa': 'A pop phenomenon, known for her empowering anthems and dynamic presence.',
	Doechii: 'Breaking barriers with her unique sound and powerful lyrical storytelling.',
	'David Kushner': 'A rising talent, creating music that resonates with a generation.',
	'David Guetta': 'A legend in the electronic music world, constantly innovating and entertaining.',
	Dave: 'A master of words, blending rap with social commentary and raw emotion.',
	Coldplay: 'Global icons in rock, known for their anthemic songs and impactful lyrics.',
	'Chris Molitor':
		'Delivering heartfelt music that speaks to the soul, blending folk and indie vibes.',
	'Chencho Corleone':
		'A dynamic presence in reggaeton, known for his catchy beats and vibrant performances.',
	'Charlie Puth': 'A pop maestro, combining catchy melodies with his exceptional musical talent.',
	Bizarrap: 'Revolutionizing the music scene with his unique production style and collaborations.',
	'Billie Eilish': 'An icon in modern pop, known for her haunting vocals and introspective lyrics.',
	'Big One':
		'Bringing a unique energy to every track, fusing various styles into a cohesive sound.',
	'Bebe Rexha': 'A dynamic voice in pop music, known for her powerful vocals and catchy tunes.',
	'Bad Bunny':
		'A trailblazer in Latin trap and reggaeton, known for his charismatic style and innovative music.',
	BTS: 'A global phenomenon, setting new standards in K-pop with their music and performances.',
	Ayparia: 'Delivering a unique blend of sounds, showcasing versatility and artistic depth.',
	'Ariana Grande': 'A powerhouse vocalist, dominating pop with her range and iconic style.',
	'Arctic Monkeys': 'Rock innovators, known for their sharp lyrics and compelling sound.'
};

const getRandomPhrase = () => bioPhrases[Math.floor(Math.random() * bioPhrases.length)];

export const getPhrase = (artistName: string) => {
	if (artistBios[artistName]) return artistBios[artistName];
	return getRandomPhrase();
};
